Repository GSS-Cogs/dd-cms, pull requests merged in 2022-07, with the labels that each got.

#433 ArticleHeader Updates
  volto/src/addons/volto-climatechange-elements/src/components/CcArticleHeader/CcArticleHeader.jsx
  volto/src/addons/volto-climatechange-elements/src/components/CcV2Preview/CcV2ArticleView.jsx
Labels: climate change 2

#440 Phase Banner bottom border removed
  volto/src/addons/volto-govuk-theme/theme/_custom.scss
Labels: climate change 2

#443 Added margin for login page
  volto/src/addons/volto-govuk-theme/theme/_custom.scss
Labels: climate change 2, capability

#458 Issue 451/phase banner
  volto/src/addons/volto-govuk-theme/src/customizations/volto/components/theme/Breadcrumbs/Breadcrumbs.jsx
  volto/src/addons/volto-govuk-theme/src/customizations/volto/components/theme/Breadcrumbs/__snapshots__/Breadcrumbs.test.jsx.snap
Labels: climate change 2, capability

#401 Add about tab and remove dropdown from articles section on nav, #393
  tests/climate-change-v2/features/overview.feature
  volto/src/addons/volto-climatechange-elements/src/components/CcSuperNavigationHeader/components/SuperNavigationHeaderMenuItem.jsx
  volto/src/addons/volto-climatechange-elements/src/components/CcSuperNavigationHeader/layout-super-navigation-header.js
  volto/src/addons/volto-climatechange-elements/src/customizations/volto/components/theme/Header/Header.jsx
  volto/src/addons/volto-climatechange-elements/theme/ClimateChange/CcSuperNavigationHeader/styles/_custom.scss
  volto/src/addons/volto-climatechange-elements/theme/ClimateChange/CcSuperNavigationHeader/styles/_layout-super-navigation-header.scss
Labels: climate change 2

#414 Import articles to initial site
  plone-5/instance/src/ukstats.ccv2.content_types/src/ukstats/ccv2/content_types/profiles/default/types/Document.xml
  plone-5/instance/src/ukstats.ccv2.content_types/src/ukstats/ccv2/content_types/profiles/default/types/Folder.xml
  tests/climate-change-v2/features/overview.feature
Labels: climate change 2

#467 Issue 392/hero header phase banner
  volto/src/addons/volto-climatechange-elements/src/components/CcHeroHeader/CcHeroHeaderView.jsx
  volto/src/addons/volto-climatechange-elements/src/components/CcMasthead/CcMasthead.jsx
  volto/src/addons/volto-climatechange-elements/theme/ClimateChange/CcHeroHeader/_ccHeroHeader.scss
  volto/src/addons/volto-climatechange-elements/theme/ClimateChange/CcMasthead/_ccMasthead.scss
Labels: climate change 2, capability

#472 List Article Extended
  plone-5/instance/src/ukstats.ccv2.content_types/src/ukstats/ccv2/content_types/profiles/default/types/Folder.xml
Labels: climate change 2, capability

#477 Issue 468/Dashboard Menus
  volto/src/addons/volto-climatechange-elements/src/components/CcSuperNavigationHeader/CcSuperNavigationHeader.jsx
  volto/src/addons/volto-climatechange-elements/src/customizations/volto/components/theme/Header/Header.jsx
  volto/src/addons/volto-climatechange-elements/src/index.js
Labels: capability
